### ISSUE TITLE
Format for date-time missing across API spec

### ISSUE THREAD

**Issue by someone1** [Yodlee/OpenAPI#2]
The OpenAPI 2.0 specification allows for data types such as `date-time` to enhance the basic types. Adding this data will make generated clients much more useful, for example:

```yaml
  ClientCredentialToken:
    type: "object"
    title: "ClientCredentialToken"
    properties:
      expiresIn:
        format: "int32"
        description: "Time in seconds after which the issued accessToken expires.<br><br><b>Endpoints</b>:<ul><li>POST /auth/token</li></ul>"
        readOnly: true
        type: "integer"
      issuedAt:
        description: "The date and time on which accessToken was created for the customer.<br><br><b>Endpoints</b>:<ul><li>POST /auth/token</li></ul>"
        readOnly: true
        type: "string"
        format: date-time
      accessToken:
        description: "Access Token to access YSL 1.1 services.<br><br><b>Endpoints</b>:<ul><li>POST /auth/token</li></ul>"
        readOnly: true
        type: "string"
```

I can see that `format` is being used for other types, in this example, the `int32` format for the `integer` type.

References:
- https://swagger.io/specification/v2/#data-types
