### ISSUE TITLE
Missing required parameter for /accounts/{accountID} endpoint

### ISSUE THREAD

**Issue by someone1** [Yodlee/OpenAPI#4]
commit 343be0ffcc49c7427ccd4047eadbe0ee9650f999 erroneously dropped the following from the swagger spec, which is required according to the [API reference docs](https://developer.yodlee.com/api-reference?destination=node/249597&autologout_timeout=1#!/accounts/getAccountDetails).

```yaml
        - in: "query"
        allowEmptyValue: false
        name: "container"
        description: "bank/creditCard/investment/insurance/loan/reward/bill/realEstate/otherAssets/otherLiabilities"
        type: "string"
        required: true
```
